%% mostly generated by erlias
-module(pl).
-compile(export_all).
set(Arg1,Arg2,Arg3) -> ds:set(Arg1,Arg2,Arg3).
set(Arg1,Arg2) -> ds:set(Arg1,Arg2).
get_list(Arg1,Arg2,Arg3) -> ds:get_list(Arg1,Arg2,Arg3).
get_list(Arg1,Arg2) -> ds:get_list(Arg1,Arg2).
get(Arg1,Arg2,Arg3) -> ds:get(Arg1,Arg2,Arg3).
get(Arg1,Arg2) -> ds:get(Arg1,Arg2).
has_key(Arg1,Arg2) -> ds:has_key(Arg1,Arg2).
update(Arg1,Arg2,Arg3) -> ds:update(Arg1,Arg2,Arg3).
boolize(Arg1,Arg2) -> ds:boolize(Arg1,Arg2).
atomize(Arg1,Arg2) -> ds:atomize(Arg1,Arg2).
transform(Arg1,Arg2) -> ds:transform(Arg1,Arg2).
map(Arg1,Arg2) -> ds:map(Arg1,Arg2).
rekey(Arg1,Arg2,Arg3) -> ds:rekey(Arg1,Arg2,Arg3).
rekey(Arg1,Arg2) -> ds:rekey(Arg1,Arg2).
delete_list(Arg1,Arg2) -> ds:delete_list(Arg1,Arg2).
delete(Arg1,Arg2) -> ds:delete(Arg1,Arg2).
keep(Arg1,Arg2) -> ds:keep(Arg1,Arg2).
filter(Arg1,Arg2) -> ds:filter(Arg1,Arg2).
merge(Arg1,Arg2) -> ds:merge(Arg1,Arg2).
merge(Arg1) -> ds:merge(Arg1).
guess_merge(Arg1) -> ds:guess_merge(Arg1).
guess_merge(Arg1,Arg2) -> ds:guess_merge(Arg1,Arg2).
compare(Arg1,Arg2,Arg3) -> ds:compare(Arg1,Arg2,Arg3).
to_list(Arg1) -> ds:to_list(Arg1).
to_dict(Arg1) -> ds:to_dict(Arg1).
to_map(Arg1) -> ds:to_map(Arg1).
type(Arg1) -> ds:type(Arg1).
